package com.lens.chatter.enums;

/**
 * Created by Emir Gökdemir
 * on 2 May 2020
 */

public enum SearchOperator {
    BETWEEN_AREA,
    BETWEEN_AREA_DEFECTS,
    BETWEEN_TIME,
    EQUAL,
    EQUAL_DEFECTS_DEFECT_TYPE_KEY,
    EQUAL_FOR_SPECIFIC,
    FROM,
    GREATER_THAN,
    GREATER_THAN_EQUAL,
    IN,
    LESS_THAN,
    LESS_THAN_EQUAL,
    MATCH,
    MATCH_DEFECTS_DEFECT_TYPE_KEY,
    MATCH_DEFECT_KEY,
    MATCH_DEFECT_TYPE_KEY,
    MATCH_END,
    MATCH_FOR_SPECIFIC,
    MATCH_PRODUCT_TYPE_KEY,
    MATCH_START,
    NOT_EQUAL,
    NOT_IN,
    TO
}
